# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up default python version
      run : |
        pip install toml
        VERSION_NUMBER=$(python extract_python_version.py)
        echo "PYTHON_VERSION=${VERSION_NUMBER}" >> $GITHUB_ENV
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install --group pyproject.toml:lint
        uv pip install --group pyproject.toml:test
        uv pip install --group pyproject.toml:build
        uv pip install -r pyproject.toml
    - name: Lint with pylint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        source .venv/bin/activate
        pylint --fail-under=3  --output-format=github src
    - name: Formatting with black
      run: |
        source .venv/bin/activate
        black --check src

    - name: Test with pytest
      run: |
        source .venv/bin/activate
        commit_sha=$(git rev-parse HEAD)
        branch=$(git rev-parse --abbrev-ref HEAD)
        python -m pytest --cov=src --cov-report=html:coverage --html-output=pytest-html-report --git-commit=$commit_sha --git-branch=$branch
      shell: bash

    - name: Upload coverage and test report
      uses: actions/upload-artifact@v4
      with:
        name: pytest results
        path: |
          coverage/
          pytest-html-report/
    - name: build
      run: |
        source .venv/bin/activate
        python -m build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: |
          dist/*.whl
          dist/*.tar.gz